### ISSUE TITLE
Invalid Google Links

### ISSUE THREAD

**Issue by kaleb** [pygments/pygments.github.io#1]
Any links from google that I get for your website are getting 404. Google is sending me to https://pygments.org/docs/api which is not found, but https://pygments.org/docs/api.html is found. I think something got changed in the way you are generating your pages that shut off pretty URLs or something and Google has not caught up.

**Comment by Anteru** [comment]
@birkenfeld Is there a way to make Sphinx generate the right structure here (i.e. `/topic/index.html`)? I suspect we could also manually generate some pages to redirect/keep the old links working. Any thoughts?

**Comment by birkenfeld** [comment]
we can use the `dirhtml` writer instead of `html`.

**Comment by birkenfeld** [comment]
OK, dirhtml is used now. Thanks for the report!
